version: '3.8'

services:
  mysql:
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    container_name: smartspace-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    container_name: smartspace-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

  backend:
    ports:
      - "8080:8080"
      - "5005:5005" # JPDA debug port
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      SPRING_PROFILES_ACTIVE: dev
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
