package com.smartspace.entry.service;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.smartspace.booking.entity.Booking;
import com.smartspace.booking.repository.BookingRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class EvidenceService {

    private final BookingRepository bookingRepository;

    public EvidenceService(BookingRepository bookingRepository) {
        this.bookingRepository = bookingRepository;
    }

    @Transactional(readOnly = true)
    public byte[] generateEvidencePdf(Long bookingId) {
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, out);
            document.open();

            document.add(new Paragraph("SmartSpace Handover Evidence Pack"));
            document.add(new Paragraph("Booking Reference: BK-" + booking.getId()));
            document.add(new Paragraph("Hall: " + booking.getHall().getName()));
            document.add(new Paragraph("Renter: " + booking.getUser().getFirstName() + " " + booking.getUser().getLastName()));
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm");
            document.add(new Paragraph("Scheduled Start: " + booking.getSlotStart().format(dtf)));
            document.add(new Paragraph("Scheduled End: " + booking.getSlotEnd().format(dtf)));
            document.add(new Paragraph("Status: " + booking.getStatus()));

            // Additional details can be added here (Checklists, photos, etc.)
            document.add(new Paragraph("\n--- \nGenerated by SmartSpace Trusted Audit"));

            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }
}
