CREATE TABLE pricing_suggestions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hall_id BIGINT NOT NULL REFERENCES halls(id),
    day_of_week VARCHAR(20) NOT NULL,
    start_hour INT NOT NULL,
    end_hour INT NOT NULL,
    suggestion_type VARCHAR(50) NOT NULL, -- SURGE, DISCOUNT
    percentage INT NOT NULL,
    rationale_json JSON,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING, APPLIED, DISMISSED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (hall_id, day_of_week, start_hour, end_hour)
);

CREATE TABLE waitlist_entries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    hall_id BIGINT NOT NULL REFERENCES halls(id),
    start_time TIMESTAMP NOT NULL,
    duration_minutes INT NOT NULL,
    guest_count INT NOT NULL,
    event_type VARCHAR(100),
    status VARCHAR(50) NOT NULL DEFAULT 'WAITING', -- WAITING, OFFERED, CONVERTED, EXPIRED, CANCELLED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
