CREATE TABLE society_members (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    hall_id BIGINT NOT NULL REFERENCES halls(id),
    status VARCHAR(50) NOT NULL, -- PENDING, APPROVED, REJECTED
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, hall_id)
);

CREATE TABLE pricing_suggestions (
    id BIGSERIAL PRIMARY KEY,
    hall_id BIGINT NOT NULL REFERENCES halls(id),
    day_of_week VARCHAR(20) NOT NULL,
    start_hour INT NOT NULL,
    end_hour INT NOT NULL,
    suggestion_type VARCHAR(50) NOT NULL, -- SURGE, DISCOUNT
    percentage INT NOT NULL,
    rationale_json JSONB,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING, APPLIED, DISMISSED
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (hall_id, day_of_week, start_hour, end_hour)
);

CREATE TABLE waitlist_entries (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    hall_id BIGINT NOT NULL REFERENCES halls(id),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes INT NOT NULL,
    guest_count INT NOT NULL,
    event_type VARCHAR(100),
    status VARCHAR(50) NOT NULL DEFAULT 'WAITING', -- WAITING, OFFERED, CONVERTED, EXPIRED, CANCELLED
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
